version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "poetry run python manage.py makemigrations &&
             poetry run python manage.py migrate &&
             poetry run python manage.py create_superuser &&
             poetry run python manage.py runserver 0.0.0.0:8080"
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: adminpassword
      DJANGO_SUPERUSER_EMAIL: admin@example.com
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      DATABASE_URL: postgres://myuser:mypassword@db:5432/mydb
      REDIS_URL: redis://redis:6379/0
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    networks:
      - eq_network


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - eq_network


  redis:
    image: "redis:alpine"
    networks:
      - eq_network

volumes:
  postgres_data:

networks:
  eq_network:
    driver: bridge
    name: eq_network